project_id = "rljbkkwzqnvawizyyzzb"

[functions.create-hospital-users]
verify_jwt = false

[functions.create-health-office-users]
verify_jwt = false

[functions.create-provincial-users]
verify_jwt = false

[functions.create-hospital-users-provincial]
verify_jwt = false

[functions.create-health-office-users-provincial]
verify_jwt = false
